apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hrm-app.fullname" . }}
  labels:
    {{- include "hrm-app.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.springProfile | quote }}
  JAVA_TOOL_OPTIONS: {{ .Values.javaOpts | quote }}
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
