package com.vatek.hrmtoolnextgen.enumeration;

public enum EUserPosition {
    FRONTEND_DEVELOPER,
    BACKEND_DEVELOPER,
    FULLSTACK_DEVELOPER,
    MANUAL_TESTER,
    AUTOMATIC_TESTER,
    FULLSTACK_TESTER,
    QUALITY_CONTROL,
    BUSINESS_ANALYSIS,
    DIRECTOR,
    CEO,
    SOLUTION_ARCHITECTURE,
    DEV_OPS,
    SALE_MANAGER,
    ACCOUNTING,
    PROJECT_MANAGER,
    TECHNICAL_MANAGER,
    HUMAN_RESOURCE,
}
